### ISSUE TITLE
building failed : unable to change directory to $ACE_ROOT\contrib\mimizip

### ISSUE THREAD

**Issue by jhenchen** [DOCGroup/CoSMIC#1]
when I run the following command to generate CoSMIC_GAME.sln:
perl %ACE_ROOT%\bin\mwc.pl -type vc14 CoSMIC_GAME.mwc
I got the error:
Unable to change directory to D:/my_ace/ACE_wrappers/contrib/mimizip.

**Comment by jhenchen** [comment]
The latest ACE_TAO version does not contain that directory.

**Comment by jwillemsen** [comment]
This got moved in the latest release, please update the corresponding mwc file to use DANCE_ROOT instead of ACE_ROOT and open a new pull request for integrating the fix

**Comment by jwillemsen** [comment]
Updated the mpc files to use DANCE_ROOT
